import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/components/theme/theme-provider";

import { AppSidebar } from "@/components/navbar/app-sidebar";
import { AnimatedThemeToggler } from "@/components/theme/animated-theme-toggler";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <AppSidebar>{children}</AppSidebar>
          <AnimatedThemeToggler duration={900} />
        </ThemeProvider>
      </body>
    </html>
  );
}
